// @ts-check
// It is easiest for `ace build` to read js files, so that is why this is a js file


/**
 * - A fundamental is a file that has helpful stuff in it
 * - A collection of these files is a plugin
 * - Users opt into fundamentals by opting into plugins
 * - Types
 *     - `copy`: Simply copy the content from the src folder to their output folder
 *     - `helper`: Not a fundamental but helps them
 *     - `custom`: Copy + Custom implementation
 */
class Fundamental {
  /**
   * @param {string} ext - File extension
   * @param {'solid' | 'zod' | 'valibot' | 'turso' | 'agGrid' | 'cf' | 'markdownIt' | 'brevo' | 'vanilla' | 'chartjs' | 'hljs' | 'lottie'} pluginName - Name of plugin
   * @param {'copy' | 'helper' | 'custom'} type - Type of fundamental
   */
  constructor(ext, pluginName, type) {
    this.ext = ext
    this.type = type
    this.pluginName = pluginName
  }
}


export const fundamentals = new Map([
  ['a', new Fundamental('tsx', 'solid', 'copy')],
  ['aceMarkdown', new Fundamental('tsx', 'solid', 'copy')],
  ['aceResponse', new Fundamental('ts', 'solid', 'copy')],
  ['agBooleanFilter', new Fundamental('ts', 'agGrid', 'copy')],
  ['agGrid.types', new Fundamental('ts', 'agGrid', 'copy')],
  ['agGrid', new Fundamental('tsx', 'agGrid', 'copy')],
  ['agGridCellRenderer', new Fundamental('tsx', 'agGrid', 'copy')],
  ['agGridComponent', new Fundamental('ts', 'agGrid', 'copy')],
  ['agShowColumn', new Fundamental('ts', 'agGrid', 'copy')],
  ['api', new Fundamental('ts', 'solid', 'copy')],
  ['async', new Fundamental('ts', 'solid', 'copy')],
  ['atom', new Fundamental('ts', 'solid', 'copy')],
  ['base.styles', new Fundamental('css', 'vanilla', 'copy')],
  ['base64UrlDecode', new Fundamental('ts', 'vanilla', 'copy')],
  ['base64UrlEncode', new Fundamental('ts', 'vanilla', 'copy')],
  ['bytes', new Fundamental('ts', 'vanilla', 'copy')],
  ['buildUrl', new Fundamental('ts', 'solid', 'copy')],
  ['callApi', new Fundamental('ts', 'solid', 'copy')],
  ['callRouteComponent', new Fundamental('ts', 'solid', 'copy')],
  ['carousel.styles', new Fundamental('css', 'solid', 'copy')],
  ['carousel', new Fundamental('tsx', 'solid', 'copy')],
  ['chartjs', new Fundamental('tsx', 'solid', 'copy')],
  ['createAceKey', new Fundamental('ts', 'solid', 'copy')],
  ['createApiUrl', new Fundamental('ts', 'solid', 'copy')],
  ['createAtoms', new Fundamental('ts', 'solid', 'copy')],
  ['createFormDataObject', new Fundamental('ts', 'vanilla', 'copy')],
  ['createOnNavigationKeyDown', new Fundamental('ts', 'vanilla', 'copy')],
  ['createOnSubmit', new Fundamental('ts', 'solid', 'copy')],
  ['createPositionPopover', new Fundamental('ts', 'solid', 'helper')],
  ['createRouteUrl', new Fundamental('ts', 'solid', 'copy')],
  ['createStreamGuard', new Fundamental('ts', 'vanilla', 'helper')],
  ['createStyleFactory', new Fundamental('ts', 'solid', 'copy')],
  ['createAtomsProvider', new Fundamental('tsx', 'solid', 'copy')],
  ['createStoreReconcile', new Fundamental('ts', 'solid', 'copy')],
  ['createStoreRefBind', new Fundamental('ts', 'solid', 'copy')],
  ['cuteLog', new Fundamental('ts', 'vanilla', 'copy')],
  ['date2Epoch', new Fundamental('ts', 'vanilla', 'copy')],
  ['date2Input', new Fundamental('ts', 'vanilla', 'copy')],
  ['date2Iso', new Fundamental('ts', 'vanilla', 'copy')],
  ['dateFromInput', new Fundamental('ts', 'vanilla', 'copy')],
  ['dateLike2Date', new Fundamental('ts', 'vanilla', 'copy')],
  ['datePast', new Fundamental('ts', 'vanilla', 'copy')],
  ['dateRead', new Fundamental('ts', 'vanilla', 'copy')],
  ['dateRelative', new Fundamental('ts', 'vanilla', 'copy')],
  ['dateShift', new Fundamental('ts', 'vanilla', 'copy')],
  ['dateTimeFormat', new Fundamental('tsx', 'vanilla', 'copy')],
  ['debounce', new Fundamental('ts', 'vanilla', 'copy')],
  ['destructureReady', new Fundamental('ts', 'vanilla', 'copy')],
  ['diff', new Fundamental('ts', 'vanilla', 'copy')],
  ['dropdown', new Fundamental('tsx', 'solid', 'copy')],
  ['dropdown.styles', new Fundamental('css', 'solid', 'copy')],
  ['enums', new Fundamental('ts', 'vanilla', 'copy')],
  ['env', new Fundamental('ts', 'vanilla', 'custom')],
  ['envs', new Fundamental('ts', 'vanilla', 'helper')],
  ['eventToPathname', new Fundamental('ts', 'solid', 'helper')],
  ['fetch', new Fundamental('tsx', 'solid', 'helper')],
  ['feComponent', new Fundamental('tsx', 'solid', 'copy')],
  ['getEnv', new Fundamental('ts', 'vanilla', 'helper')],
  ['getGoUrl', new Fundamental('ts', 'solid', 'copy')],
  ['getRequestEvent', new Fundamental('ts', 'solid', 'copy')],
  ['goResponse', new Fundamental('ts', 'solid', 'copy')],
  ['getSearchParams', new Fundamental('ts', 'solid', 'helper')],
  ['hashCreate', new Fundamental('ts', 'vanilla', 'copy')],
  ['hashValidate', new Fundamental('ts', 'vanilla', 'copy')],
  ['hljsDeclare.d', new Fundamental('ts', 'hljs', 'copy')],
  ['hljsMarkdownItOptions', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/bash', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/core', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/css', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/dart', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/dockerfile', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/go', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/graphql', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/http', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/java', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/javascript', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/json', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/php', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/scss', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/sql', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/swift', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/typescript', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/wasm', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/xml', new Fundamental('ts', 'hljs', 'copy')],
  ['hljs/yaml', new Fundamental('ts', 'hljs', 'copy')],
  ['holdUp', new Fundamental('ts', 'solid', 'copy')],
  ['indexDB', new Fundamental('ts', 'solid', 'copy')],
  ['isClickOutsideAll', new Fundamental('ts', 'vanilla', 'copy')],
  ['isFile', new Fundamental('ts', 'vanilla', 'helper')],
  ['jwtCreate', new Fundamental('ts', 'vanilla', 'copy')],
  ['jwtValidate', new Fundamental('ts', 'vanilla', 'copy')],
  ['kParse', new Fundamental('ts', 'solid', 'copy')],
  ['liveServer', new Fundamental('ts', 'cf', 'copy')],
  ['load', new Fundamental('tsx', 'solid', 'copy')],
  ['loading', new Fundamental('tsx', 'solid', 'copy')],
  ['loading.styles', new Fundamental('css', 'solid', 'copy')],
  ['lorem', new Fundamental('ts', 'solid', 'copy')],
  ['lottie', new Fundamental('tsx', 'lottie', 'copy')],
  ['merge', new Fundamental('ts', 'vanilla', 'copy')],
  ['modal.styles', new Fundamental('css', 'solid', 'copy')],
  ['modal', new Fundamental('tsx', 'solid', 'copy')],
  ['ms', new Fundamental('ts', 'vanilla', 'copy')],
  ['msCreate', new Fundamental('ts', 'vanilla', 'copy')],
  ['messagesCleanup', new Fundamental('tsx', 'solid', 'helper')],
  ['messages', new Fundamental('tsx', 'solid', 'copy')],
  ['onApi404', new Fundamental('ts', 'solid', 'helper')],
  ['onClean', new Fundamental('ts', 'solid', 'copy')],
  ['pathname2Segments', new Fundamental('ts', 'solid', 'helper')],
  ['parseError', new Fundamental('ts', 'solid', 'copy')],
  ['parseMarkdownFolders', new Fundamental('ts', 'solid', 'custom')],
  ['pick', new Fundamental('ts', 'vanilla', 'copy')],
  ['populateScopeComponent', new Fundamental('ts', 'solid', 'helper')],
  ['pulse.styles', new Fundamental('css', 'solid', 'copy')],
  ['pulse', new Fundamental('tsx', 'solid', 'copy')],
  ['r2', new Fundamental('ts', 'vanilla', 'copy')],
  ['r2Url', new Fundamental('ts', 'vanilla', 'copy')],
  ['r2Worker', new Fundamental('ts', 'cf', 'copy')],
  ['radioCards.styles', new Fundamental('css', 'solid', 'copy')],
  ['radioCards', new Fundamental('tsx', 'solid', 'copy')],
  ['randomArrayItem', new Fundamental('ts', 'solid', 'copy')],
  ['randomBetween', new Fundamental('ts', 'solid', 'copy')],
  ['readBody', new Fundamental('ts', 'solid', 'helper')],
  ['refClear', new Fundamental('ts', 'solid', 'copy')],
  ['refFormReset', new Fundamental('ts', 'solid', 'copy')],
  ['refModel', new Fundamental('ts', 'solid', 'copy')],
  ['refs', new Fundamental('ts', 'solid', 'copy')],
  ['resolveAlias', new Fundamental('ts', 'solid', 'helper')],
  ['rootLayout', new Fundamental('ts', 'solid', 'copy')],
  ['route', new Fundamental('ts', 'solid', 'copy')],
  ['route404', new Fundamental('ts', 'solid', 'copy')],
  ['scopeBE', new Fundamental('ts', 'solid', 'copy')],
  ['scopeComponent', new Fundamental('tsx', 'solid', 'copy')],
  ['scopeComponentContext', new Fundamental('ts', 'solid', 'copy')],
  ['scopeComponentProvider', new Fundamental('tsx', 'solid', 'copy')],
  ['scopeComponentChildren', new Fundamental('ts', 'solid', 'helper')],
  ['scopeComponentMessages', new Fundamental('ts', 'solid', 'helper')],
  ['selectPlaceholder', new Fundamental('ts', 'solid', 'copy')],
  ['sendBrevoTemplate', new Fundamental('ts', 'brevo', 'copy')],
  ['slideshow.styles', new Fundamental('css', 'solid', 'copy')],
  ['slideshow', new Fundamental('tsx', 'solid', 'copy')],
  ['smoothFor', new Fundamental('ts', 'solid', 'copy')],
  ['stream', new Fundamental('tsx', 'solid', 'copy')],
  ['submit', new Fundamental('tsx', 'solid', 'copy')],
  ['subLayout', new Fundamental('ts', 'solid', 'copy')],
  ['swAddOffLineSupport', new Fundamental('js', 'solid', 'copy')],
  ['swRegister', new Fundamental('js', 'solid', 'copy')],
  ['tabs.styles', new Fundamental('css', 'solid', 'copy')],
  ['tabs', new Fundamental('tsx', 'solid', 'copy')],
  ['toast.styles', new Fundamental('css', 'solid', 'copy')],
  ['toast', new Fundamental('tsx', 'solid', 'copy')],
  ['tooltip.styles', new Fundamental('css', 'solid', 'copy')],
  ['tooltip', new Fundamental('tsx', 'solid', 'copy')],
  ['tron', new Fundamental('tsx', 'solid', 'copy')],
  ['tron.styles', new Fundamental('css', 'solid', 'copy')],
  ['treeCreate', new Fundamental('ts', 'solid', 'helper')],
  ['treeSearch', new Fundamental('ts', 'solid', 'helper')],
  ['tursoConnect', new Fundamental('ts', 'turso', 'copy')],
  ['types', new Fundamental('ts', 'solid', 'custom')],
  ['useScope', new Fundamental('ts', 'solid', 'copy')],
  ['useChartJs', new Fundamental('ts', 'solid', 'copy')],
  ['useNetworkStatus', new Fundamental('ts', 'solid', 'copy')],
  ['vars', new Fundamental('ts', 'vanilla', 'copy')],
  ['vanilla', new Fundamental('ts', 'vanilla', 'custom')],
  ['vBool', new Fundamental('ts', 'valibot', 'copy')],
  ['vDate', new Fundamental('ts', 'valibot', 'copy')],
  ['vEmail', new Fundamental('ts', 'valibot', 'copy')],
  ['vImg', new Fundamental('ts', 'valibot', 'copy')],
  ['vFile', new Fundamental('ts', 'valibot', 'copy')],
  ['vEnums', new Fundamental('ts', 'valibot', 'copy')],
  ['vNum', new Fundamental('ts', 'valibot', 'copy')],
  ['vParse', new Fundamental('ts', 'valibot', 'copy')],
  ['vParser', new Fundamental('ts', 'valibot', 'copy')],
  ['vString', new Fundamental('ts', 'valibot', 'copy')],
  ['vSearchParamsArray', new Fundamental('ts', 'valibot', 'copy')],
  ['zParse', new Fundamental('ts', 'zod', 'copy')],
])
